services:
  db:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pkm
      POSTGRES_PASSWORD: pkm
      POSTGRES_DB: pkm
    ports:
      - '5432:5432'
    volumes:
      - pkm_db_data:/var/lib/postgresql/data

volumes:
  pkm_db_data:
