-- Restores the HNSW index dropped by phase5_assistant_chat's autogenerated
-- diff (Prisma's diff engine doesn't know this hand-written index is
-- supposed to exist — see the comment in that migration for the full
-- explanation). Net effect across the two migrations: no change.
CREATE INDEX IF NOT EXISTS "embeddings_vector_hnsw_idx" ON "embeddings" USING hnsw ("vector" vector_cosine_ops);
