-- Restores the HNSW index dropped by albo_subphase_a_collections's
-- autogenerated diff — same recurring hazard as the Phase 5 restore
-- migration (Prisma's diff engine doesn't know this hand-written index is
-- supposed to exist). Net effect across the two migrations: no change.
CREATE INDEX IF NOT EXISTS "embeddings_vector_hnsw_idx" ON "embeddings" USING hnsw ("vector" vector_cosine_ops);
