-- NOTE: prisma migrate dev's autogenerated diff included
-- `DROP INDEX "embeddings_vector_hnsw_idx"` here, same recurring hazard
-- documented in ARCHITECTURE.md since Phase 5 — Prisma's diff engine has no
-- schema-level knowledge that this hand-written raw-SQL index is supposed
-- to exist. Removed from this migration; see the follow-up restore
-- migration.

-- AlterTable
ALTER TABLE "saved_items" ADD COLUMN     "importanceScore" DOUBLE PRECISION,
ADD COLUMN     "lastViewedAt" TIMESTAMP(3),
ADD COLUMN     "saveReason" TEXT;

-- CreateTable
CREATE TABLE "collections" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "emoji" TEXT,
    "isAiSuggested" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "collections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "saved_item_collections" (
    "savedItemId" TEXT NOT NULL,
    "collectionId" TEXT NOT NULL,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "saved_item_collections_pkey" PRIMARY KEY ("savedItemId","collectionId")
);

-- CreateIndex
CREATE UNIQUE INDEX "collections_userId_name_key" ON "collections"("userId", "name");

-- AddForeignKey
ALTER TABLE "collections" ADD CONSTRAINT "collections_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item_collections" ADD CONSTRAINT "saved_item_collections_savedItemId_fkey" FOREIGN KEY ("savedItemId") REFERENCES "saved_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saved_item_collections" ADD CONSTRAINT "saved_item_collections_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "collections"("id") ON DELETE CASCADE ON UPDATE CASCADE;
